name: AWS
on:
  push:
    branches:
      - main
jobs:
  integration:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3
      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Compilacion"
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target
      - name: Contenedor Docker
        run: |
          docker build -t prueba .
          docker images
          docker run --name webgoat -d -p 8080:8080 -p 9090:9090 prueba
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Carga imagen a ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/a5e9s9c6
          docker tag prueba:latest public.ecr.aws/a5e9s9c6/daniel_repo:latest
          docker push public.ecr.aws/a5e9s9c6/daniel_repo:latest

      - name: Descarga de terraform
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan -out tfplan
          terraform apply tfplan >> results_tfplan.txt
          ipp=$(cat results_tfplan.txt | grep My_ip | xargs | cut -d '=' -f 2)
          sed -i "s/IP/$ipp/g" ../ansible/inventario
         # terraform plan -destroy -out tfplan

      - name: Descarga checkov
        run: |
          cd terraform/
          pip3 install checkov
          terraform show -json tfplan | jq > tfplan.json
          checkov -f tfplan.json
        continue-on-error: true

      - name: Ansible
        env: 
          PRIVATE_KEY: ${{ secrets.CLAVES_CHAMBA }}
        run: |
          sudo apt update
          sudo apt install ansible -y
          pip3 install "ansible-lint"
          cd ansible/
          echo "$PROVATE_KEY" >> $HOME/claves_chamba.pem
          sudo chmod 600 $HOME/claves_chamba.pem
          export ANSIBLE_HOST_KEY_CHEKING=False
          ansible-playbook -i inventario server.yaml --become --private-key $HOME/claves_chamba.pem
        continue-on-error: true

      - name: Arachni
        run: |
          cd terraform/
          wget https://github.com/Arachni/arachni/releases/download/v1.6.1.3/arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          tar -xvf arachni-1.6.1.3-0.6.1.1-linux-x86_64.tar.gz
          ipp=$(cat results_tfplan.txt | grep My_ip | xargs | cut -d '=' -f 2)
          ./arachni-1.6.1.3-0.6.1.1/bin/arachni --check=* http://ipp:8080/WebGoat/login

      - name: Parado y eliminando contenedor
        run: |
          cd terraform
          terraform plan -destroy -out tfplan
          terraform apply tfplan
          docker container stop webgoat
          docker container rm webgoat