name: Docker
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Creando"
        run: docker pull php:7.0-apache
  
      - name: "Docker Imagen"
        run: docker images